@baseUrl = {{$processEnv IAP_BASE_URL}}
@token = Bearer {{$processEnv IAP_ACCESS_TOKEN}}

### WORKFLOWS

GET {{baseUrl}}/v1/workflows
?pageSize=5
&sort=timeCreated desc
Authorization: {{token}}

### WORKFLOW-RUNS

GET {{baseUrl}}/v1/workflows/runs
?pageSize=5
&sort=timeCreated desc
Authorization: {{token}}

### WORKFLOW details given WFL

@workflowid = wfl.7c9294790eb147dc973e1d6a1ce6aa62
GET {{baseUrl}}/v1/workflows/{{workflowid}}
Authorization: {{token}}

### WORKFLOW versions given WFL

// @name workflowversions
GET {{baseUrl}}/v1/workflows/{{workflowid}}/versions
?pageSize=5
&sort=timeCreated desc
Authorization: {{token}}

### WORKFLOW version details given WFL, version name

@versionid = {{workflowversions.response.body.$.items[0].version}}
GET {{baseUrl}}/v1/workflows/{{workflowid}}/versions/{{versionid}}
?pageSize=5
&sort=timeCreated desc
Authorization: {{token}}

### WORKFLOW-RUN details given WFR

@workflowrunid = wfr.98f1971f92af4b1a998bbaf0321541f6
GET {{baseUrl}}/v1/workflows/runs/{{workflowrunid}}
Authorization: {{token}}


### WORKFLOW-RUN history given WFR

GET {{baseUrl}}/v1/workflows/runs/{{workflowrunid}}/history
?pageSize=500
&sort=eventId asc
Authorization: {{token}}
