@baseUrl = {{$processEnv IAP_BASE_URL}}
@token = Bearer {{$processEnv IAP_ACCESS_TOKEN}}


### Parent

// @name workflow
POST {{baseUrl}}/v1/workflows
Authorization: {{token}}
Content-Type: application/json

{
    "name": "PD_dragen_somatic",
    "description": "dragen somatic testing"
}

### Version

# @workflowid = {{workflow.response.body.$.id}}
@workflowid = wfl.126aeca88a614aa5a5cacd470a47136b

// @name workflowversion
POST {{baseUrl}}/v1/workflows/{{workflowid}}/versions
Authorization: {{token}}
Content-Type: application/json

< ./dragenSomaticFastqInput/version.json

### Launch

# @vname = {{workflowversion.response.body.$.version}}
@vname = dragenSomaticFastqInput
// @name workflowrun
POST {{baseUrl}}/v1/workflows/{{workflowid}}/versions/{{vname}}:launch
Authorization: {{token}}
Content-Type: application/json

< ./dragenSomaticFastqInput/launch.json

### History

# @workflowrunid = @{{workflowrun.response.body.$.id}}
@workflowrunid = wfr.50c7447d87e94d9b9e238040eeade26f
GET {{baseUrl}}/v1/workflows/runs/{{workflowrunid}}/history
?pageSize=100
&sort=eventId
Authorization: {{token}}

### ABORT WORKFLOW RUN

# @abort_wfrunid = wfr.85b646c7408a4a93b63026dc0979d226
PUT {{baseUrl}}/v1/workflows/runs/{{abort_wfrunid}}:abort
Authorization: {{token}}
Content-Type: application/json

{
    "error": "wrongDragenImage",
    "cause": "UsePublic"
}

### PATCH Workflow Version

PATCH {{baseUrl}}/v1/workflows/{{workflowid}}/versions/{{vname}}
Authorization: {{token}}
Content-Type: application/json

< ./dragenSomaticFastqInput/version_patched.json