@baseUrl = {{$processEnv IAP_BASE_URL}}
@token = Bearer {{$processEnv IAP_ACCESS_TOKEN}}


### Parent

// @name workflow
POST {{baseUrl}}/v1/workflows
Authorization: {{token}}
Content-Type: application/json

{
  "name": "PD_echo",
  "description": "echo testing"
}


### Version

@workflowid = {{workflow.response.body.$.id}}
# @workflowid = wfl.3e6b9eb5c41844ff8e97ba52aedfa0d5

// @name workflowversion
POST {{baseUrl}}/v1/workflows/{{workflowid}}/versions
Authorization: {{token}}
Content-Type: application/json

< ./echoToStdoutRedirect/version.json

### Launch

# @vname = {{workflowversion.response.body.$.version}}
@vname = echoToStdoutRedirect
// @name workflowrun
POST {{baseUrl}}/v1/workflows/{{workflowid}}/versions/{{vname}}:launch
Authorization: {{token}}
Content-Type: application/json

< ./echoToStdoutRedirect/launch_test1.json


### History

# @workflowrunid = @{{workflowrun.response.body.$.id}}
@workflowrunid = wfr.1ed63b21c6b1430d80c510c4f15839a9
GET {{baseUrl}}/v1/workflows/runs/{{workflowrunid}}/history
?pageSize=100
&sort=eventId
Authorization: {{token}}

### ABORT WORKFLOW RUN

# @abort_wfrunid = {{workflowrunid}}
# PUT {{baseUrl}}/v1/tasks/runs/{{abort_wfrunid}}:abort
# Authorization: {{token}}